---
name: Upgrade 2.6

on:
  repository_dispatch:
    types:
      - geomapfish_2.6_updated

jobs:
  upgrade:
    runs-on: ubuntu-18.04
    name: Upgrade 2.6
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - prod-2-6
          - prod-2-6-simple

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.GITHUB_GOPASS_CI_TOKEN }}

      - name: Update the demo
        run: >
          scripts/upgrade ${{ github.event.client_payload.version }} origin
      - name: Push interrupted Upgrade
        run: |
          ls -als .UPGRADE*
          git add --all || true
          git add --force .UPGRADE_INSTRUCTIONS upgrade .upgrade.yaml || true
          git status
          git commit -m "Interrupted upgrade to ${{ github.event.client_payload.version }}"
          git push --force origin HEAD:interrupted-upgrade-${{ matrix.branch }}-${{ github.event.client_payload.version }}
          python3 -c 'import requests
          responce = requests.post(
              "https://api.github.com/repos/camptocamp/demo_geomapfish/pulls",
              json={
                "title": "Upgrade failed",
                "body": "See https://github.com/camptocamp/demo_geomapfish/actions?query=workflow%3A%22Upgrade+2.6%22",
                "head": "interrupted-upgrade-${{ matrix.branch }}-${{ github.event.client_payload.version }}",
                "base": "${{ matrix.branch }}",
                "maintainer_can_modify": True
              },
              headers={
                  "Accept": "application/vnd.github.v3+json",
                  "Authorization": "Bearer ${{ secrets.GITHUB_GOPASS_CI_TOKEN }}",
                  "Content-Type": "application/json",
              },
          )
          assert responce.status_code < 300, responce.text'
        if: failure()
